otel-metrics-pipeline:
  workers: 2
  delay: 5000
  source:
    otel_metrics_source:
      ssl: false
      port: 21891
      authentication:
        unauthenticated: {}
  processor:
    - otel_metrics:
        calculate_histogram_buckets: true
        calculate_exponential_histogram_buckets: true
        exponential_histogram_max_allowed_scale: 10
        flatten_attributes: false
    - flatten:
        source: attributes
        target: ""
        remove_processed_fields: true
    - rename_keys:
        entries:
          - from_key: resource.attributes.position
            to_key: position
          - from_key: resource.attributes.site@name
            to_key: site-name
          - from_key: resource.attributes.city
            to_key: city
          - from_key: resource.attributes.region
            to_key: region
          - from_key: resource.attributes.postcode
            to_key: postcode
          - from_key: resource.attributes.state
            to_key: state
          - from_key: metric.attributes.sip@health
            to_key: sip-health
          - from_key: metric.attributes.capillary@health
            to_key: capillary-health
          - from_key: metric.attributes.ghl@health
            to_key: ghl-health
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index: otlp-metrics
        username: admin
        password: admin
        ssl:
          insecure: true

otel-logs-pipeline:
  workers: 2
  delay: 3000
  source:
    otel_logs_source:
      ssl: false
      port: 21892
      authentication:
        unauthenticated: {}
  processor:
    - grok:
        match:
          body:
            - "%{TIMESTAMP_ISO8601:log_timestamp} %{LOGLEVEL:level} \\[%{DATA:source}\\] %{GREEDYDATA:message}"
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index: otlp-logs
        username: admin
        password: admin
        ssl:
          insecure: true
