otel-logs-pipeline:
  workers: 2
  delay: 3000
  source:
    otel_logs_source:
      ssl: false
      port: 21892
      authentication:
        unauthenticated: {}
  processor:
    - grok:
        match:
          body:
            - "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} \\[%{DATA:source}\\](?:\\s+\\[(?:%{NUMBER:pid}|-)\\])?\\s+%{GREEDYDATA:message}"  
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index: otlp-logs
        username: admin
        password: admin
        ssl:
          insecure: true
