otel-logs-pipeline:
  workers: 2
  delay: 3000
  source:
    otel_logs_source:
      ssl: false
      port: 21892
      authentication:
        unauthenticated: {}
  processor:
    - grok:
        match:
          body:
            # Pattern for filelog (hub-gw logs)
            - "%{TIMESTAMP_ISO8601:log_timestamp} %{LOGLEVEL:level} \\[%{DATA:source}\\] %{GREEDYDATA:message}"
            # Pattern for syslog (RFC3164)
            - "<%{POSINT:priority}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{HOSTNAME:hostname} %{DATA:program}(?:\\[%{POSINT:pid}\\])?: %{GREEDYDATA:message}"
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index: otlp-logs
        username: admin
        password: admin
        ssl:
          insecure: true
